<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            color: #2c3e50;
            background-color: #f4f4f4;
        }
        .container {
            padding: 50px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        h1 {
            color: #34495e;
            text-align: center;
            font-size: 2.5em;
        }
        p {
            font-size: 1.2em;
            line-height: 1.6;
        }
        .dynamic-data {
            margin-top: 30px;
            padding: 20px;
            background-color: #ecf0f1;
            border-left: 5px solid #3498db;
            color: #2c3e50;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ $title }}</h1>
        <p>This PDF was successfully generated from a Laravel Blade view using Puppeteer and Browsershot.</p>
        <p>This demonstrates the seamless integration of a Node.js process within a Laravel application.</p>
        
        <div class="dynamic-data">
            <h3>Example Data:</h3>
            <ul>
                <li><strong>Current Time:</strong> {{ $currentTime }}</li>
                <li><strong>Random Number:</strong> {{ $randomNumber }}</li>
                <li><strong>Generated By:</strong> Laravel Application</li>
            </ul>
        </div>
    </div>
</body>
</html>